package oops;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Rashmit Mhatre
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public Signup() {
        initComponents();
        jPasswordField1.setEchoChar((char) 0);
        jPasswordField2.setEchoChar((char) 0);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("HP Simplified", 1, 60)); // NOI18N
        jLabel1.setText("WELCOME TO SIGNUP ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jTextField1.setText("Enter Name");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 170, 30));

        jTextField2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jTextField2.setText("Enter Email");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 250, 30));

        jTextField3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jTextField3.setText("Enter Username");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 180, 30));

        jPasswordField1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jPasswordField1.setText("Enter Password");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 170, 30));

        jPasswordField2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jPasswordField2.setText("Enter Password");
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 170, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup_1.png"))); // NOI18N
        jButton1.setText("Signup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 521, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 140, 40));

        jLabel3.setFont(new java.awt.Font("HP Simplified", 0, 24)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 70, -1));

        jLabel4.setFont(new java.awt.Font("HP Simplified", 0, 24)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 70, -1));

        jLabel5.setFont(new java.awt.Font("HP Simplified", 0, 24)); // NOI18N
        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 110, 30));

        jLabel6.setFont(new java.awt.Font("HP Simplified", 0, 24)); // NOI18N
        jLabel6.setText("Create Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 180, -1));

        jLabel7.setFont(new java.awt.Font("HP Simplified", 0, 24)); // NOI18N
        jLabel7.setText("Confirm Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 190, -1));

        jCheckBox1.setFont(new java.awt.Font("HP Simplified", 0, 18)); // NOI18N
        jCheckBox1.setText("Check Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 150, 30));

        jCheckBox2.setFont(new java.awt.Font("HP Simplified", 0, 18)); // NOI18N
        jCheckBox2.setText("Check Password");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 445, 150, 30));

        jLabel8.setFont(new java.awt.Font("HP Simplified", 0, 24)); // NOI18N
        jLabel8.setText("Phone Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 160, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jTextField4.setText("Enter Phone Number");
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 160, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, -1));

        jLabel2.setFont(new java.awt.Font("HP Simplified", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/images/hand-drawn-minimal-background_23-2149017896 - Copy.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            jPasswordField1.setEchoChar((char) 0);
        } else {
            jPasswordField1.setEchoChar('*');
        }
    }// GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2.isSelected()) {
            jPasswordField2.setEchoChar((char) 0);
        } else {
            jPasswordField2.setEchoChar('*');
        }
    }// GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (areFieldsEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        } else if (!doPasswordsMatch()) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.");
        } else if (!isPhoneNumberValid()) {
            JOptionPane.showMessageDialog(this, "Enter a valid 10-digit phone number.");
        } else if (isUserAlreadyExists()) {
            // Username already exists, show a dialog box
            JOptionPane.showMessageDialog(null, "Username already exists", "Duplicate Username",
                    JOptionPane.ERROR_MESSAGE);
        } else if (isPhoneAlreadyExists()) {
            // Phone number already exists, show a dialog box
            JOptionPane.showMessageDialog(null, "Phone Number already exists", "Duplicate Phone Number",
                    JOptionPane.ERROR_MESSAGE);
        } else if (isEmailAlreadyExists()) {
            // Email already exists, show a dialog box
            JOptionPane.showMessageDialog(null, "Email already exists", "Duplicate Email", JOptionPane.ERROR_MESSAGE);
        } else if (enterPasswords()) {
            // Email already exists, show a dialog box
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Password !! ", "Inavlid Password",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            // All checks passed, proceed with inserting the new record
            insertUser();
        }
    }

    private boolean enterPasswords() {

        return String.valueOf(jPasswordField1.getPassword()).equals("Enter Password");
    }

    private boolean areFieldsEmpty() {
        return jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty() ||
                jTextField4.getText().isEmpty() || String.valueOf(jPasswordField1.getPassword()).isEmpty() ||
                String.valueOf(jPasswordField2.getPassword()).isEmpty();
    }

    private boolean doPasswordsMatch() {
        return Arrays.equals(jPasswordField1.getPassword(), jPasswordField2.getPassword());
    }

    private boolean isPhoneNumberValid() {
        String phoneText = jTextField4.getText();
        return phoneText.length() == 10 && phoneText.matches("\\d+");
    }

    private boolean isUserAlreadyExists() {
        String username = jTextField3.getText();
        // Query to check if the username already exists
        String checkQuery = "SELECT username FROM login WHERE username = ?";
        return isFieldAlreadyExists(checkQuery, username);
    }

    private boolean isPhoneAlreadyExists() {
        String phoneText = jTextField4.getText();
        // Query to check if the phone number already exists
        String checkQuery = "SELECT phone_number FROM login WHERE phone_number = ?";
        return isFieldAlreadyExists(checkQuery, phoneText);
    }

    private boolean isEmailAlreadyExists() {
        String email = jTextField2.getText();
        // Query to check if the email already exists
        String checkQuery = "SELECT email FROM login WHERE email = ?";
        return isFieldAlreadyExists(checkQuery, email);
    }

    private boolean isFieldAlreadyExists(String query, String field) {
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student", "root", "root")) {
            PreparedStatement checkSt = con.prepareStatement(query);
            checkSt.setString(1, field);
            ResultSet checkRs = checkSt.executeQuery();
            return checkRs.next();
        } catch (Exception ex) {
            ex.printStackTrace();
            return true; // Consider error as already exists
        }
    }

    private void insertUser() {
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student", "root", "root")) {
            String name = jTextField1.getText();
            String email = jTextField2.getText();
            String username = jTextField3.getText();
            String phoneText = jTextField4.getText();
            long phone = Long.parseLong(phoneText);

            char[] passwordChars = jPasswordField1.getPassword();
            String password = new String(passwordChars); // Assuming passwords are hashed in the database

            // Query to insert a new user
            String insertQuery = "INSERT into login (name, email, username, password, phone_number) values (?, ?, ?, ?, ?)";
            PreparedStatement insertSt = con.prepareStatement(insertQuery);
            insertSt.setString(1, name);
            insertSt.setString(2, email);
            insertSt.setString(3, username);
            insertSt.setString(4, password);
            insertSt.setLong(5, phone);

            insertSt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Registration Successful!");
            dispose();
            new Login().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jPasswordField1.setText("Enter Password");
        jPasswordField2.setText("Enter Password");
        jTextField1.setText("Enter Name");
        jTextField2.setText("Enter Email");
        jTextField3.setText("Enter Username");
        jTextField4.setText("Enter Phone Number");

    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jButton3) {

            int choice = JOptionPane.showOptionDialog(null,
                    "Do you want to go back to the login page?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    new String[] { "Yes", "Cancel" },
                    "Yes");

            if (choice == JOptionPane.YES_OPTION) {

                new Login().setVisible(true);
                this.dispose();

            }
        }
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        if (jTextField1.getText().equals("Enter Name")) {
            jTextField1.setText("");
        }
    }// GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        if (jTextField1.getText().equals("")) {
            jTextField1.setText("Enter Name");
        }

    }// GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
        if (jTextField2.getText().equals("Enter Email")) {
            jTextField2.setText("");
        }
    }// GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        if (jTextField2.getText().equals("")) {
            jTextField2.setText("Enter Email");
        }
    }// GEN-LAST:event_jTextField2FocusLost

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField4FocusGained
        // TODO add your handling code here:
        if (jTextField4.getText().equals("Enter Phone Number")) {
            jTextField4.setText("");
        }
    }// GEN-LAST:event_jTextField4FocusGained

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
        if (jTextField4.getText().equals("")) {
            jTextField4.setText("Enter Phone Number");
        }
    }// GEN-LAST:event_jTextField4FocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField3FocusGained
        // TODO add your handling code here:
        if (jTextField3.getText().equals("Enter Username")) {
            jTextField3.setText("");
        }

    }// GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        if (jTextField3.getText().equals("")) {
            jTextField3.setText("Enter Username");
        }
    }// GEN-LAST:event_jTextField3FocusLost

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        if (String.valueOf(jPasswordField1.getPassword()).equals("Enter Password")) {
            jPasswordField1.setText("");
            jPasswordField1.setEchoChar('*'); // Set echo char to '*' for password hiding
        }

    }// GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
        if (String.valueOf(jPasswordField1.getPassword()).equals("")) {
            jPasswordField1.setText("Enter Password");
            jPasswordField1.setEchoChar((char) 0);
        }
    }// GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jPasswordField2FocusGained
        // TODO add your handling code here:
        if (String.valueOf(jPasswordField2.getPassword()).equals("Enter Password")) {
            jPasswordField2.setText("");
            jPasswordField2.setEchoChar('*'); // Set echo char to '*' for password hiding
        }

    }// GEN-LAST:event_jPasswordField2FocusGained

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jPasswordField2FocusLost
        // TODO add your handling code here:
        if (String.valueOf(jPasswordField2.getPassword()).equals("")) {
            jPasswordField2.setText("Enter Password");
            jPasswordField2.setEchoChar((char) 0);
        }

    }// GEN-LAST:event_jPasswordField2FocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
